#!/usr/bin/env bash

su www-data <<EOSU

if [ -f /var/www/html/var/composer_home/auth.json ]; then
   rm /var/www/html/var/composer_home/auth.json
fi

ln -s /var/www/.composer/auth.json /var/www/html/var/composer_home/


/var/www/html/bin/magento sampledata:deploy

/var/www/html/bin/magento setup:upgrade

/var/www/html/bin/magento setup:di:compile

EOSU
