#!/usr/bin/env bash

su www-data <<EOSU

INSTALL_DIR = /var/www/html;

if [ -f $INSTALL_DIR/var/composer_home/auth.json ]; then
   rm $INSTALL_DIR/var/composer_home/auth.json
fi

ln -s /var/www/.composer/auth.json INSTALL_DIR/var/composer_home/

$INSTALL_DIR/bin/magento maintenance:enable

$INSTALL_DIR/bin/magento sampledata:deploy

$INSTALL_DIR/bin/magento setup:upgrade

$INSTALL_DIR/bin/magento setup:di:compile

$INSTALL_DIR/bin/magento maintenance:disable

EOSU
